version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: kurs_db
    ports:
      - '3306:3306'
    networks:
      - backend
    volumes:
      - data:/var/lib/mysql

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
